version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

  db:
    restart: always
    image: mariadb:10.3
    volumes:
      - ./mariadb/db:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/mysql_log:/var/log/mysql
      - ./mariadb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
      MYSQL_USER: ahmedsamir
      MYSQL_PASSWORD: password1
